### ISSUE TITLE
Missing Plana's spine

### ISSUE THREAD

**Issue by GPBeta** [lwd-temp/blue-archive-spine-production#1]
It's funny that I can find the `arona_spr` but not the `plana_spr`, since there're both `arona_workpage_daytime` and `arona_workpage_nighttime` in the repository.

**Comment by 555zzID** [comment]
Plana's spine in the repository under the folder name ``NP0035_spr``

**Comment by GPBeta** [comment]
Wow, I see. Thank you for the information.
