### ISSUE TITLE
How do you get a link from an obb file?

### ISSUE THREAD

**Issue by ALpaFA** [lwd-temp/blue-archive-spine-production#2]
I have a question. Previously https://github.com/lwd-temp/blue-archive-spine said that to get the JsonURL, parse the obb file and find it in GameMainConfig. However, in my environment, converting from hexadecimal (HEX) to text is as follows.
How can I get the JsonURL?
thank you.
`
GameMainConfig``
rWT#Iür´WW#krµWq#ìröWI#krúWW#îrW^#lÀrWW#Úr´Wh#arøW9#PürWJ#yÛr¤WX#ìr¨W\#iÚrÿW&#
ràWl#drWL#[ér´W##yõr÷Wm#Oÿr£Wb#Mr¸WY#yrÿW9#rºWi#ûrW|#ràW7#
`

**Comment by lwd-temp** [comment]
See https://github.com/K0lb3/Blue-Archive---Asset-Downloader for decryption.
